# Generated by Django 6.0 on 2026-01-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_department_description_department_established_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
